ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cor/',include('mainapp.urls')),
    path('fee/',include('mainapp2.urls')),
]

mainapp/urls.py
from django.contrib import admin
from django.urls import path
from . import views
urlpatterns = [
    path('about/',views.about),
    path('learndj/',views.learn_django,name="django"),
    path('learnpy/',views.learn_python,name="python"),
    path('info/',views.info),
    path('reg/',views.registration,name='reg'),
    path('mgrreg/',views.mgrRegistration,name='mgrreg'),
]

mainapp2/urls.py
from django.contrib import admin
from django.urls import path
from mainapp2 import views
urlpatterns = [
    path('feedj/',views.fees_django),
    path('feepy/',views.fees_python),
    path('info1/',views.info1),
    path('signup/',views.signup,name='signup'),  
    path('login/',views.userlogin,name='login'),
    path('profile/',views.profile,name='profile'),
    path('dashboard/',views.dashboard,name='dashboard'),
    # path('userdetails/<int:eid>',views.userDetails,name='userdetails'),
    path('logout/',views.userlogout,name='logout'),
    path('pass/',views.changepass,name='pass'),
    path('setcookie/',views.setCookie,name='setcookie'),
    path('getcookie/',views.getCookie,name='getcookie'),
]

mainapp2/models.py
from django.db import models

# Create your models here.

class Blog(models.Model):
    title=models.CharField(max_length=100)
    desc=models.CharField(max_length=200)

mainapp2/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    password2=forms.CharField(label="RePassword",widget=forms.PasswordInput)
    class Meta:
        model=User
        fields=['username','first_name','last_name','email']
        labels={'email':"User Email"}

class EditUserProfileCreation(UserChangeForm):
    Password=None
    class Meta:
        model=User
        fields=['username','first_name','last_name','email','date_joined']
        labels={'email':"User Email"}

class EditAdminProfileCreation(UserChangeForm):
    Password=None
    class Meta:
        model=User
        fields='__all__'
        labels={'email':"User Email"}

mainapp2/views.py
from django.shortcuts import render,HttpResponseRedirect
# from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .forms import SignUpForm,EditUserProfileCreation,EditAdminProfileCreation
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm,PasswordChangeForm,SetPasswordForm
from django.contrib.auth import authenticate,login,logout,update_session_auth_hash 
from django.contrib.auth.decorators import login_required
# Create your views here.
def fees_django(request):
      return render(request,'fees/djfees.html')
def fees_python(request):
      return render(request,'fees/pyfees.html')
def info1(request):
      return render(request,'info/info.html')
# def signup(request):
#       print("Hello")
#       if(request.method=="POST"):
#             print("Hello2")
#             fm=UserCreationForm(request.POST)
#             print("Hello3")
#             if(fm.is_valid()):
#                   print("Valid Data")
#             return render(request,'fees/signup.html',{'Form':fm})
#       else:
#             fm=UserCreationForm()
#       return render(request,'fees/signup.html',{'Form':fm})


def signup(request):  
      if(request.method=="POST"):         
            fm=SignUpForm(request.POST)
            if(fm.is_valid()): 
                  fm.save()               
                  messages.success(request,"Account is Created")            
      else: 
            fm=SignUpForm()
      return render(request,'fees/signup.html',{'Form':fm})

def userlogin(request):
   # if user not login 
   if(not request.user.is_authenticated):
      if(request.method=="POST"):
         log=AuthenticationForm(request=request,data=request.POST)  
         print("Hello")
         if(log.is_valid()):
               print("Valid Data") 
               uname=log.cleaned_data['username']
               pwd=log.cleaned_data['password']  
               print(uname,pwd)
               #matched data from the database
               user=authenticate(username=uname,password=pwd)
               if( user is not None ):
                  print("Authenticated user")
                  #if user have correct data 
                  login(request,user)                 
                  return HttpResponseRedirect('/fee/dashboard/')      
      else:
            log=AuthenticationForm()
      return render(request,'fees/login.html',{'Login':log})

   else:
      # if user has already login 
      return HttpResponseRedirect('/fee/profile/') 


def profile(request):
      # if user has already login 
      if(request.user.is_authenticated):
          if(request.method=="POST"):  
            if(request.user.is_superuser==True): 
                        print("Hello Admin")
                        pfl=EditAdminProfileCreation(request.POST,instance=request.user)
                        if(pfl.is_valid()):
                              print("Valid Admin")
                              pfl.save()
                              messages.success(request,"Admin Profile Updated!!!!") 
                        users=User.objects.all()                             
            else:          
                 pfl=EditUserProfileCreation(request.POST,instance=request.user)
                 print("Hello User")
                 if(pfl.is_valid()):
                       messages.success(request,"User Profile Updated!!!!")
                       pfl.save()
                 users=None 
          else:
            if(request.user.is_superuser==True):
                 pfl=EditAdminProfileCreation(instance=request.user)
                 users=User.objects.all()  
            else:
                 pfl=EditUserProfileCreation(instance=request.user) 
                 users=None
          return render(request,'fees/profile.html',{"Profile":pfl,"User":request.user.get_full_name()})
      else: 
            # if user not login 
           return HttpResponseRedirect('/fee/login/')

# def userDetails(request,eid):
#       if(request.user.is_authenticated):
#             pi=User.objects.get(pk=eid)
#             user=EditUserProfileCreation(instance=pi) 
#             return render(request,'fees/profiledetails.html',{"Profile":user})
#       else:
#             return HttpResponseRedirect('/fee/login/')

def dashboard(request):
      # if user has already login 
      if(request.user.is_authenticated):
      
          return render(request,'fees/dashboard.html',{"User":request.user.get_full_name()})
      else: 
            # if user not login 
           return HttpResponseRedirect('/fee/login/')

def userlogout(request):
      logout(request)
      return HttpResponseRedirect('/fee/login/')

# with old password
# def changepass(request):
#  # if user has already login 
#  if(request.user.is_authenticated):     
#    if(request.method=="POST"):
#       changepwd=PasswordChangeForm(user=request.user,data=request.POST)
#       if(changepwd.is_valid()):
#             changepwd.save() 
#             update_session_auth_hash(request,changepwd.user)
#             messages.success(request,"Password has been changed successfully!!!!")
#             return HttpResponseRedirect('/fee/profile/')
#    else:   
#             changepwd=PasswordChangeForm(user=request.user)
#    return render(request,'fees/changepass.html',{"Change":changepwd})
#  else:
#        # if user not login 
#       return HttpResponseRedirect('/fee/login/')


# with new password
def changepass(request):
 # if user has already login 
 if(request.user.is_authenticated):     
   if(request.method=="POST"):
      changepwd=SetPasswordForm(user=request.user,data=request.POST)
      if(changepwd.is_valid()):
            changepwd.save() 
            update_session_auth_hash(request,changepwd.user)
            messages.success(request,"Password has been changed successfully!!!!")
            return HttpResponseRedirect('/fee/profile/')
   else:   
            changepwd=SetPasswordForm(user=request.user)
   return render(request,'fees/changepass.html',{"Change":changepwd})
 else:
       # if user not login 
      return HttpResponseRedirect('/fee/login/')


def setCookie(request):
      response=render(request,'fees/setcookie.html')
      re=response.set_cookie('name','Arpita')
      print(re)
      return response

def getCookie(request):
      name=request.COOKIES['name']
      print(name)
      return render(request,'fees/getcookie.html',{"Name":name})

mainapp2/templates/fees/changepass.html
{% extends 'course/base.html' %}
{% load static %}
{% block title %}{{block.super}} | Change Password {% endblock title %}
{% block content %}

<h1><center>Change Password </center></h1>
<form action="" method="POST" novalidate >
{% csrf_token %}

 <table>

   
{% for field in Change %}
{{field.label_tag}}{{field}}{{field.errors|striptags}}</br></br>
{% endfor %}
</table>

<input type="Submit" value="Save Password">
</form>

<a href="{% url 'profile' %}">Profile</a>

{% endblock content %}

mainapp2/templates/fees/dashboard.html
{% extends 'course/base.html' %}
{% load static %}
{% block title %}{{block.super}} | Dashboard Page{% endblock title %}
{% block content %}

<h1><center>Dashboard Page</center></h1>
{{User}}
{% if perms.mainapp2.delete_blog %}
<input type="button" value="Delete"></br>
{% endif %}  
<a href="{% url 'profile' %}">profile</a>  
<a href="{% url 'logout' %}">Logout</a>
{% endblock content %}

mainapp2/templates/fees/djfees.html
<!DOCTYPE html>
<html lang="en">
<head>
<body>
    
    Feee Django
</body>
</html>

mainapp2/templates/fees/getcookie.html
{% extends 'course/base.html' %}
{% load static %}
{% block title %}{{block.super}} | Get Cookie Page{% endblock title %}
{% block content %}

<h1><center>Get Cookie Page</center></h1>
<p>Welcome Get Cookie Page</p>
{{Name}}
<a href="{% url 'dashboard' %}">Dashboard</a>
<a href="{% url 'logout' %}">Logout</a>
<a href="{% url 'pass' %}">Change password</a>
{% endblock content %}

mainapp2/templates/fees/login.html
{% extends 'course/base.html' %}
{% load static %}
{% block title %}{{block.super}} | Login Page{% endblock title %}
{% block content %}
<style>
    .err{
        color:red;
    }
</style>
<h1><center>Login</center></h1>
<form action="" method="POST" novalidate >
{% csrf_token %}

 <table>
{% if Login.non_field_errors %}
    {% for error in Login.non_field_errors  %}
      <p class="err">{{error}}</p>
    {% endfor %}
  {% endif %} 

{% for field in Login %}
{{field.label_tag}}{{field}}{{field.errors|striptags}}</br></br>
{% endfor %}
</table>

<input type="Submit" value="Submit">
</form>
{% if messages %}
{% for message in messages %}
<strong>
 {% if message.tags %}
{{message}}
{% endif %}
</strong>
{% endfor %}
{% endif %}
<a href="{% url 'signup' %}">Sign Up</a>

{% endblock content %}

mainapp2/templates/fees/profile.html
{% extends 'course/base.html' %}
{% load static %}
{% block title %}{{block.super}} | Profile Page{% endblock title %}
{% block content %}

<h1><center>Profile Page</center></h1>
<p>Welcome</p>
{% comment %} <style>
    .success
    {color:red;}
</style>
{% if messages %}
{% for message in messages %}
<strong>
 {% if message.tags %}
<p class="success">{{message}}</p>
{% endif %}
</strong>
{% endfor %}
{% endif %}
{{Name}}<br> {% endcomment %}
<b>{{User}}</b></br>

{% if messages %}
{% for message in messages %}
<strong>
 {% if message.tags %}
{{message}}
{% endif %}
</strong>
{% endfor %}
{% endif %}

<!--your page -->
<!-- {% if info != None %}
    <h3>All User Data</h3>
    {% for  user in info %}
        <a href="{% url 'userdetails' user.eid %}">{{user.username}}</a></br>
    {% endfor %}
{% endif %} -->
<form action="" method="POST" novalidate >
    {% csrf_token %}
     <table>
    {% for field in Profile %}
    {{field.label_tag}}{{field}}{{field.errors|striptags}}</br></br>
    {% endfor %}
    </table>
    <input type="Submit" value="Save">   
<form>
<a href="{% url 'dashboard' %}">Dashboard</a>
<a href="{% url 'logout' %}">Logout</a>
<a href="{% url 'pass' %}">Change password</a>
{% endblock content %}

mainapp2/templates/fees/pyfees.html
<!DOCTYPE html>
<html lang="en">
<head>
<body>
    
    Python Fees
</body>
</html>

mainapp2/templates/fees/setcookie.html
{% extends 'course/base.html' %}
{% load static %}
{% block title %}{{block.super}} | Set Cookie Page{% endblock title %}
{% block content %}

<h1><center>Set Cookie Page</center></h1>
<p>Welcome Set Cookie Page</p>

<a href="{% url 'dashboard' %}">Dashboard</a>
<a href="{% url 'logout' %}">Logout</a>
<a href="{% url 'pass' %}">Change password</a>
{% endblock content %}

mainapp2/templates/fees/signup.html
{% extends 'course/base.html' %}
{% load static %}
{% block title %}{{block.super}} | SignUp Page{% endblock title %}
{% block content %}

<h1><center>Sign Up</center></h1>
<form action="" method="POST" novalidate >
{% csrf_token %}

 <table>

   
{% for field in Form %}
{{field.label_tag}}{{field}}{{field.errors|striptags}}</br></br>
{% endfor %}
</table>

<input type="Submit" value="Submit">
</form>
{% if messages %}
{% for message in messages %}
<strong>
 {% if message.tags %}
{{message}}
{% endif %}
</strong>
{% endfor %}
{% endif %}
<a href="{% url 'login' %}">login</a>
{% endblock content %}

mainapp2/templates/fees/userdetails.html
{% extends 'course/base.html' %}
{% load static %}
{% block title %}{{block.super}} | Profile Details Page{% endblock title %}
{% block content %}

<h1><center>Profile Details Page</center></h1>

{{Profile}}
{% comment %} <form action="" method="POST" novalidate >
    {% csrf_token %}
     <table>
    {% for field in Info %}
    {{field.label_tag}}{{field}}{{field.errors|striptags}}</br></br>
    {% endfor %}
    </table>
    <input type="Submit" value="Save">   
<form> {% endcomment %}
<a href="{% url 'logout' %}">Logout</a>
<a href="{% url 'pass' %}">Change password</a>
{% endblock content %}